### ISSUE TITLE
Data donation Liss Panel results in participant links that show a 500 Server Error 

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#686]
**Describe the bug**
See title. 

Panel 'liss' doesn't work but Panel 'other' link works fine. 

**To Reproduce**
1. create a new project
2. create a new data donation item
3. select panel "link"
4. visit the link url (published or not doesn't matter)

**Expected behavior**
Start of participant workflow

**Screenshots**
https://github.com/eyra/mono/assets/88683839/73794792-b240-4f68-a0d3-c260614942b0

**Desktop (please complete the following information):**
macos sarari

**Comment by emielvdveen** [comment]
Fixed the issue and return a 403 since the url needs a query string with specific parameters to work. This parameters are set by the Centerdata software that connect with our Data Donation service. 

In the CMS the bare url is shown since this is the url that needs to be send to the representative of Centerdata to setup the survey on their side.

**Comment by emielvdveen** [comment]
![Image](https://github.com/eyra/mono/assets/262448/bcae6e5e-610f-4cc7-8c1a-69d5cffc73f8)

**Comment by TjerkNan** [comment]
Confirm solved
