### ISSUE TITLE
Data uploaded in preview mode is actually stored

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#888]
**Describe the bug**
When uploading data in preview mode, the data should not actually be donated and stored in storage. 
When data is donated in preview mode and storage is visited, it is observed that a file is donated.

**To Reproduce**
1. create data donation study
2. create storage (local) 
3. Add data donation step in workflow with appropriate zip
4. Open preview
5. Donate data in preview
6. Go to storage card
7. Observe donated data in preview

**Expected behavior**
No data to be stored when data donated in preview.

**Screenshots**
![Screenshot 2024-06-26 at 23 18 37](https://github.com/eyra/mono/assets/88683839/799415dc-a93a-4e40-983f-a1972cb71189)

**Desktop (please complete the following information):**
 - Safari

**Comment by emielvdveen** [comment]
@TjerkNan this is by design. Creators can test everything before publish. This becomes more important when we introduce licenses.

Solution for possible confusion:

1. Creators can delete all files before publish. This feature will be implemented soon.
2. I will change the participant id to "preview" iso a real id so the files can always be recognized.

I will use this ticket to implement the second solution

**Comment by emielvdveen** [comment]
When starting preview flow, the participant will be set "preview". This way the creator can always distinguish real donations from testing.

![Image](https://github.com/eyra/mono/assets/262448/6e0cb17d-d80a-4b6c-bfc6-c0074d55d391)

**Comment by TjerkNan** [comment]
Seems to work, I notice participant=preview
