### ISSUE TITLE
internal storage card file view should show only basename of filename

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#890]
**Describe the bug**
Filename should only contain 'basename' of file name. Current filename shows entire S3 storage 'path'. 
Maybe donated filename should have a different filename that makes sense.

**To Reproduce**
1. donate file in preview mode 
2. Observe donated file 

**Expected behavior**

- Only filename itself as zip, not as json file type
- Size to reflect donated file (is this dummy data?)
- Path of file storage not shown, only 'basename' not 'dirname'. 

**Screenshots**
![Screenshot 2024-06-26 at 23 18 37](https://github.com/eyra/mono/assets/88683839/63e3ae71-7748-491b-8afd-1387213c554d)

**Desktop (please complete the following information):**
 - safari

**Comment by emielvdveen** [comment]
@TjerkNan this is by design. This is a file browser (like finder). There is no such thing as a basename of the files. The files names have key=value pairs, thats all we have.

All files are json files. Exporting all the json files as zip is not implemented yet. Will be implemented soon in a new tab `Exports`.
