### ISSUE TITLE
[Storage] CMS: monitor metrics

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#898]
Implement the following metrics:

1. Number of store requests
2. Nr of bytes written to storage. 

Note: If the storage is emptied (see: #891) the monitor metrics are not reset. So 2 is this a sum of the total written bytes (traffic volume) not the current stored bytes.

**Comment by emielvdveen** [comment]
![Image](https://github.com/eyra/mono/assets/262448/86f300ad-1e1f-4d7a-b2ef-b78aa17b6b14)

**Comment by emielvdveen** [comment]
@TjerkNan for the future: 

1. what extra metrics would be useful?
2. Can we set thresholds on the metrics to to raise awareness by giving them a color (orange or red)?

**Comment by TjerkNan** [comment]
Maybe add: Total storage used in GB.

Just my opinion: 

- you might consider moving the file count to this screen
- Store requests and kb transfered may not be meaningfull information for non-it people and I'm not sure if it tells me anything
- we might set a soft quota on capacity and show how much of X GB is used just to give a sense that storage is not unlimited
- we might set a soft quota on the number of files stored if it turns out during my testing that large file counts may hurt performance.

**Comment by emielvdveen** [comment]
@TjerkNan In general Monitor is based on system events. Actual data is not part of the Monitor.

For storage currently have nr of write requests (most of the time the same as nr of files) and transferred bytes (most of the time the same as stored bytes).

For storage the Monitor is not really necessary. But to be consistent with other CMS pages it is added.

**Comment by emielvdveen** [comment]
See the follow up improvements:

1. #918 
2. #917

**Comment by TjerkNan** [comment]
@emielvdveen #918 tested, keep this open for #917 when ready

**Comment by TjerkNan** [comment]
as discussed this can be closed
