### ISSUE TITLE
Consent form text not visible at ( i )

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#904]
**Describe the bug**
When you enter text in the Consent form CMS, this text is not shown when you preview the workflow and visit the bottom-left i button and press 'consent'. Just an empty page.

**To Reproduce**
Steps:
- Write text at consent form part in CMS
- Go to preview
- Click i
- Click Consent
- See empty consent page
- 
**Expected behavior**
Visible Consent form text from CMS.

**Screenshots**

https://github.com/eyra/mono/assets/88683839/9f19a379-4b65-4a88-af0e-a3074a5b79ae

**Desktop (please complete the following information):**
 - safari

**Comment by emielvdveen** [comment]
@TjerkNan the signature is stored in preview mode. The Consent in ( i ) menu shows the signature text, not the latest text from the CMS. 

Possible solutions:

1. Remove Consent from ( i ) in preview mode
2. Keep Consent in ( i ) and add text in modal view after click: No signature found
3. Save the signature and accept the warning in the CMS when changing the consent text. Consent text is locked on specific version when one or more signature are linked to that version. This warning was previously found unwanted by @TjerkNan so this was fixed by not storing the signature in preview mode. 

What do you suggest?

In general: Preview mode can not be 100% like normal flow. We need to accept little differences to make it work. For me it is not perfectly clear how preview may differentiate from normal.

**Comment by AdrienneMendrik** [comment]
@emielvdveen and @TjerkNan I think we should go for solution 3. I think having the warning is less of an issue then not seeing the consent page in preview mode. This allows researchers to check the consent page. In the future we can see if we can come up with a different warning to make people aware of the underlying system (solution 4). But that is not necessary for this release.

**Comment by louwrentius** [comment]
I think for now a solution is found. 

For me personally, I expect a preview to be ephemeral and have no 'lasting side effects'. However, I understand that we want to provide creators with a capability to verify the workings of the monitor and the storage and the current mechanism is how this works. 

Maybe we might consider a button that says 'cleanup preview data' to reset state after testing within preview mode?
So we basically keep what we have and allow testing of monitor and storage. But we allow the creator (and tester) to cleanup after themselves. In that case extra ok with option 3 because during testing I can do a preview, and then discard the preview data. Or deliberately NOT discard data and see the warning message in action for testing purposes.

**Comment by emielvdveen** [comment]
@louwrentius Reset preview is an interesting idea. I will discuss this with @neocheungdesigneyra as a general concept for the near future. We can maybe combine this a clear indication during previewing that it is a preview of the flow.

For now I will implement option 3.

**Comment by emielvdveen** [comment]
@AdrienneMendrik @TjerkNan I made one `preview specific feature` until we have the `reset feature` as mentioned above. When previewing the consent onboarding page will not be visible if the creator has a signature. However, when de consent text is changed, the creator gets to see the consent onboarding page again to test. Normal participants will not get to see the consent onboarding screen twice. 

We might have such a feature in the future where we could mark the version of the consent as "major change" to force participants to resign the consent agreement. This feature needs a careful design and should not be rushed.

**Comment by TjerkNan** [comment]
I make changes and I get the warning
Then I refresh, losing changes but then changes are stored without warning
I preview and see consent info 
I continue and press i and see correct consent info in preview
